---
name: GroupsKits
author: JUZEXMOD
main: GroupsKits\Main
version: 1.0
api: [2.0.0]

commands:
  kitvip:
    description: Kitvip Command
    use: "/kitvip"
    permission: groupskits.kitvip
  kityt:
    description: Kityt Command
    use: "/kityt"
    permission: groupskits.kityt
  kitplayer:
    description: Kitplayer Command
    use: "/kitplayer"
    permission: groupskits.kitplayer
    
permission:
  groupskits.kitvip:
    description: "Kitplayer Command"
    default: op
  groupskits.kityt:
    description: "Kityt Command"
    default: op
  groupskits.kitplayer:
    description: "Kitplayer Command"
    default: true
